# Generated by Django 4.0.3 on 2022-05-26 19:45

import annoying.fields
import avisos.models.base
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Borrador'), (1, 'Publicado'), (2, 'Activo'), (3, 'Retrasado'), (4, 'Llegado'), (5, 'Cancelado')], default=0)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('max_end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('arrival_confirmation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('first_surname', models.CharField(max_length=100)),
                ('second_surname', models.CharField(blank=True, max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('use_middlename', models.BooleanField(default=False)),
                ('use_second_surname', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default='default.png', upload_to='profile_images', validators=[avisos.models.base.file_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='avisos.member')),
                ('no_medical_record', models.BooleanField(default=False)),
                ('sicknesses', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('risks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShortNotice',
            fields=[
                ('basenotice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='avisos.basenotice')),
                ('location', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('avisos.basenotice',),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('main_contact', models.BooleanField(default=False)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.member')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=100)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, through='avisos.CommitteeMember', to='avisos.member'),
        ),
        migrations.CreateModel(
            name='ClubBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=100)),
                ('receivenotices', models.BooleanField(default=True)),
                ('clubboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.clubboard')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clubboard',
            name='members',
            field=models.ManyToManyField(blank=True, through='avisos.ClubBoardMember', to='avisos.member'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='basenotice',
            name='arrival_confirmation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_confirmation_by', to='avisos.member'),
        ),
        migrations.AddField(
            model_name='basenotice',
            name='cars',
            field=models.ManyToManyField(blank=True, to='avisos.car'),
        ),
        migrations.AddField(
            model_name='basenotice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.noticecategory'),
        ),
        migrations.AddField(
            model_name='basenotice',
            name='cau_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cau_contact', to='avisos.member'),
        ),
        migrations.AddField(
            model_name='basenotice',
            name='email_recipients',
            field=models.ManyToManyField(blank=True, related_name='email_recipients', to='avisos.emailrecipient'),
        ),
        migrations.AddField(
            model_name='basenotice',
            name='participants',
            field=models.ManyToManyField(blank=True, to='avisos.member'),
        ),
        migrations.AddField(
            model_name='basenotice',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to='avisos.member'),
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('main_contact', True)), fields=('main_contact', 'member'), name='unique_main_contact'),
        ),
    ]
