# Generated by Django 4.0.3 on 2022-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo_notice', models.ImageField(blank=True, null=True, upload_to='avisos/logo_notice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
