# Generated by Django 4.0.3 on 2022-06-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_globalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('first_surname', models.CharField(max_length=100)),
                ('second_surname', models.CharField(blank=True, max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergencycontact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergencycontact_phone', models.CharField(max_length=20)),
                ('emergencycontact_email', models.EmailField(max_length=254)),
                ('emergencycontact_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avisos.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
