# Generated by Django 4.0.3 on 2022-06-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0004_basenotice_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='medications',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='risks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='sicknesses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
