# Generated by Django 4.0.3 on 2022-06-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0007_noticecategory_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotice',
            name='other_transportation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basenotice',
            name='parking_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
