# Generated by Django 4.0.3 on 2022-06-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0008_basenotice_other_transportation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='group_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='first_surname',
            field=models.CharField(max_length=100),
        ),
    ]
