# Generated by Django 4.0.3 on 2022-06-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0011_car_deleted_at_clubboard_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticecategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
