# Generated by Django 4.0.3 on 2022-06-26 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0012_basenotice_deleted_at_noticecategory_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avisos.member'),
        ),
    ]
