# Generated by Django 4.0.3 on 2022-06-27 15:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0014_alter_friend_member_alter_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='friend',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
