# Generated by Django 4.0.3 on 2022-06-27 16:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0015_alter_emergencycontact_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='emergencycontact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
