# Generated by Django 4.0.3 on 2022-07-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0016_alter_friend_emergencycontact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotice',
            name='waiting_task_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basenotice',
            name='waiting_task_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basenotice',
            name='waiting_task_two',
            field=models.BooleanField(default=False),
        ),
    ]
