# Generated by Django 4.0.3 on 2022-07-11 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0018_alter_basenotice_max_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenotice',
            name='max_end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='basenotice',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
