# Generated by Django 4.0.3 on 2022-07-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0019_alter_basenotice_max_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basenotice',
            name='waiting_task_one',
        ),
        migrations.RemoveField(
            model_name='basenotice',
            name='waiting_task_three',
        ),
        migrations.RemoveField(
            model_name='basenotice',
            name='waiting_task_two',
        ),
    ]
