# Generated by Django 4.0.3 on 2022-07-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0020_remove_basenotice_waiting_task_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortnotice',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shortnotice',
            name='route',
        ),
        migrations.AddField(
            model_name='basenotice',
            name='location',
            field=models.CharField(default='Cerro Genérico', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basenotice',
            name='route',
            field=models.CharField(default='Polaca', max_length=100),
            preserve_default=False,
        ),
    ]
