# Generated by Django 4.0.3 on 2022-07-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0022_globalsettings_notice_arrival_mail_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotice',
            name='email_late_alert_recipients',
            field=models.ManyToManyField(blank=True, related_name='email_late_alert_recipients', to='avisos.emailrecipient'),
        ),
    ]
