# Generated by Django 4.0.3 on 2022-08-11 23:02

import avisos.models.notice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0023_basenotice_email_late_alert_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenotice',
            name='max_end_date',
            field=models.DateTimeField(blank=True, default=avisos.models.notice.datetime_now_rounder),
        ),
        migrations.AlterField(
            model_name='basenotice',
            name='start_date',
            field=models.DateTimeField(blank=True, default=avisos.models.notice.datetime_now_rounder),
        ),
    ]
