# Generated by Django 4.0.3 on 2022-08-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0024_alter_basenotice_max_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotice',
            name='arrival_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basenotice',
            name='arrival_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basenotice',
            name='arrival_result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
