# Generated by Django 4.0.3 on 2022-08-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0025_basenotice_arrival_conditions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='risks',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='risks',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='basenotice',
            name='include_pdf',
            field=models.BooleanField(default=True),
        ),
    ]
