# Generated by Django 4.0.3 on 2022-08-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0026_rename_risks_friend_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
